policies:
  cleanEnvironment: true
  relativeIncludes: true
  allRelocatable: true
  offlineBuild: true
  secureSSL: true
  mergeEnvironment: true
  sandboxInvariant: true
  tidyUrlScm: true
  scmIgnoreUser: true
  sandboxFingerprints: false
  noUndefinedTools: false
